version: "3.8"

services:
  backend:
    build:
      context: ./backend-conectar
      dockerfile: Dockerfile
    container_name: conectar-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend-conectar:/app
      - /app/node_modules
    command: npm run start:prod

  db:
    image: postgres:15
    container_name: conectar-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
